import { InformationCircleIcon } from '@heroicons/react/24/outline';
import { Dispatch, SetStateAction, useState } from 'react';
import { CompanyInfoComponent } from '@/components/CompanyInfoComponent';
import { ExtractedTextContent } from '@/components/ExtractedTextComponent';
import { SummaryContent } from '@/components/SummaryContent';

interface FileType {
  name: string;
  fullPath?: string;
  content?: string;
  type: 'file' | 'folder';
}

interface SelectedFilePanelProps {
  selectedFile: FileType;
  extractedTexts: Record<string, string>;
  extractedCompanies: Record<string, any[]>;
  summaries: Record<string, string>;
  showExtracted: boolean;
  setShowExtracted: Dispatch<SetStateAction<boolean>>;
  rawResponses: Record<string, string>;
}

const SelectedFilePanel = ({
  selectedFile,
  extractedTexts,
  extractedCompanies,
  summaries,
  showExtracted,
  setShowExtracted,
  rawResponses
}: SelectedFilePanelProps) => {
  const fileKey = selectedFile.fullPath || '';
  const [showRawResponse, setShowRawResponse] = useState(false);
  const fullPath = selectedFile.fullPath || '';

  return (
    <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-semibold text-gray-900">
          {selectedFile.name}
          <span className="text-sm text-gray-500 ml-2">
            ({selectedFile.type === 'file' ? 'File' : 'Folder'})
          </span>
        </h3>
        <div className="flex gap-2">
        
          {extractedCompanies[fullPath] && (
            <button
              onClick={() => setShowRawResponse(!showRawResponse)}
              className="px-3 py-1 text-sm bg-gray-100 text-gray-800 rounded-md hover:bg-gray-200"
            >
              {showRawResponse ? 'Hide Raw' : 'Show Raw'}
            </button>
          )}
        </div>
      </div>

      {/* Always show file preview */}
      <div className="mb-6 border rounded-md overflow-hidden">
        {selectedFile.content && (
          <iframe
            src={selectedFile.content}
            className="w-full h-96"
            title="File Preview"
          />
        )}
      </div>

      {/* Raw response toggleable section */}
      {showRawResponse && (
        <div className="mt-4 p-4 bg-gray-50 rounded-md border border-gray-200">
          <h4 className="text-sm font-medium mb-2 text-gray-700">Raw LLM Response</h4>
          <pre className="text-xs whitespace-pre-wrap break-words text-gray-600">
            {rawResponses[fullPath] || 'No raw response available'}
          </pre>
        </div>
      )}

      {/* Extracted content sections */}
     
          {/* Extracted Text */}
         
          {showRawResponse && extractedTexts[fileKey] && (
            <div className="mt-6">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-sm font-medium text-gray-700">Extracted Text</h4>
              </div>
              <div className="border p-3 rounded bg-gray-50 text-sm text-gray-600">
                <ExtractedTextContent content={extractedTexts[fileKey]} />
              </div>
            </div>
          )}
         

          {/* Extracted Companies */}
          {/*
          {extractedCompanies[fileKey]?.length > 0 && (
            <div className="mt-6 border-t pt-6">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm mr-2">
                  Companies
                </span>
                Extracted Entities
              </h4>
              <CompanyInfoComponent companies={extractedCompanies[fileKey]} />
            </div>
            
          )}
          */}

          {/* Summaries */}
          {summaries[fileKey] && (
            <div className="mt-6 border-t pt-6">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <span className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm mr-2">
                  AI Summary
                </span>
                Key Insights
              </h4>
              <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                <SummaryContent content={summaries[fileKey]} />
                <div className="mt-4 flex items-center text-sm text-green-700">
                  <InformationCircleIcon className="w-4 h-4 mr-1" />
                  Summary generated by AI - verify against original documents
                </div>
              </div>
            </div>
          )}
       
    </div>
  );
};

export default SelectedFilePanel;